name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      options:
        - label: I have read the CONTRIBUTING guidelines
          required: true
        - label: I have checked existing issues to avoid duplicates
          required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of EternalEconomy are you using?
      placeholder: v1.0.0
    validations:
      required: true
  - type: input
    id: server-version
    attributes:
      label: Server Version
      description: What server software and version are you using? (e.g., Paper 1.20.4)
      placeholder: Paper version git-Paper-123 (MC: 1.20.4)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: I entered the command... and then...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Paste any relevant logs or screenshots here.
      render: shell
